import Helmet from 'react-helmet'
import { Layout, PageHeader, Button, Table } from 'antd'
import { Home as Index } from '@styles/pages'
import React from 'react'
import { useAppDispatch, useAppSelector } from '@lib/hooks'
import { users } from '@slices/users'

const { Content } = Layout

function Home() {
	const dispatch = useAppDispatch()
	const userList = useAppSelector((state) => {
		const user = state.users.user
		return user ?? []
	})
	const [columns] = React.useState<{ [key: string]: any }[]>([
		{ title: 'id', dataIndex: 'id', key: 'id' },
		{ title: 'title', dataIndex: 'title', key: 'title' },
		{ title: 'client', dataIndex: 'client', key: 'client' },
		{ title: 'area', dataIndex: 'area', key: 'area' },
		{ title: 'country', dataIndex: 'country', key: 'country' },
		{
			title: 'contact',
			dataIndex: 'contact',
			key: 'contact',
			render: (contact: string) => {
				return <a>{contact}</a>
			},
		},
		{ title: 'assignee', dataIndex: 'assignee', key: 'assignee' },
	])

	const onChangeTab = (key: string) => {
		console.log('탭 전환', key)
	}

	const getUser = async () => {
		console.log(users())
		// await dispatch(users())
	}

	return (
		<Index>
			<Helmet>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Helmet>
			<PageHeader
				className="page-header"
				title="Index"
				subTitle="This is main page"
			/>
			<Content className="site-layout-content">
				<Button type="primary" onClick={getUser}>
					회원 정보 불러오기
				</Button>
				<Table dataSource={userList} columns={columns} />
			</Content>
		</Index>
	)
}

export default Home
